#cloud-config
password: Nutanix.123
chpasswd: { expire: False }
ssh_pwauth: True
apt_update: True
packages:
 - mariadb-server
 - mariadb-client
write_files:
 - content: |
    [mysqld]
    # Network Configuration
    bind-address = 0.0.0.0
    port = 3306

    # Logging
    log_error = /var/log/mysql/error.log
    slow_query_log = 1
    slow_query_log_file = /var/log/mysql/slow.log
    long_query_time = 2
    log_queries_not_using_indexes = 1

    # Character Set
    character_set_server = utf8mb4
    collation_server = utf8mb4_unicode_ci

    # Security
    skip_name_resolve = 1
    local_infile = 0

    [mysql]
    default_character_set = utf8mb4

    [client]
    default_character_set = utf8mb4
   path: /tmp/50-server.cnf
runcmd: 
 - hostname FNS-DB01
 - wget https://raw.githubusercontent.com/smmartin330/nc2-flow-lab-aws/refs/heads/main/fns_demo/lab_db.sql -O /tmp/lab_db.sql
 - mysql -e "CREATE DATABASE wordpress;"
 - mysql -e "CREATE USER 'wp_admin'@'%' IDENTIFIED BY 'Nutanix.123';"
 - mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wp_admin'@'%';"
 - mysql -e "FLUSH PRIVILEGES;"
 - mysql wordpress < /tmp/lab_db.sql
 - cp /tmp/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
 - service mariadb restart